### ISSUE TITLE
masterclass 2019 to-do

### ISSUE THREAD

**Issue by tpmccauley** [cms-outreach/ispy-webgl#113]
In preparation for 2019 version of masterclass (starting from latest on master):

- [x] Hide some functionality: animation, stereo view, and import/export geometry

- [x] Add new data files to file load menu

- [x] Do not use new Line object for muons and electrons in order to aid with picking

- [x] Implement new invariant mass functionality

- [x] Hide renderer selection in settings

- [x] Increment version and tag

- [x] Reduced ECAL

- [x] Show information dialogs by default

- [ ] ~~Links from information dialogs go to old CMS page: find new links or take content on-board into display?~~

- [x] Change default visible and hidden objects

- [x] Hide charge in table view and popups

- [x] When an event is loaded hide the Detector toggles in the tree view

- [x] Make shift+check color change when selecting tracks for invariant mass calculation persistent

**Comment by tpmccauley** [comment]
http://cern.ch/ispy-webgl-masterclass

**Comment by tpmccauley** [comment]
Issue #121 needs to be fixed before invariant mass re-do

**Comment by tpmccauley** [comment]
Some enhancements in invariant mass in #124 and problems with orthographic picking in #123

**Comment by tpmccauley** [comment]
Make a new issue for CMS webpage links and close
